import { faCode, faCodeFork, faComment, faFile, faStar } from "@fortawesome/free-solid-svg-icons"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import moment from "moment"

const Gist = (props) => {
    const { data, keyVal } = props
    return (
        <div className="gistBody" key={'gist_' + keyVal}>
            <div className="gistHead">
                <div className="leftHead">
                    <span>
                        <img src={data?.owner?.avatar_url} />
                    </span>
                    <label>{data?.owner?.login}</label>
                </div>
                <div className="rightHead">
                    <span>
                        <FontAwesomeIcon icon={faCode} />
                        <label>{Object.keys(data?.files).length} file{Object.keys(data?.files).length > 0 ? 's' : ''}</label>
                    </span>
                    <span>
                        <FontAwesomeIcon icon={faCodeFork} />
                        <label><a href={data?.forks_url} target={'_blank'}>Forks</a></label>
                    </span>
                    <span>
                        <FontAwesomeIcon icon={faComment} />
                        <label><a href={data?.comments_url} target={'_blank'}>Comments</a></label>
                    </span>
                    <span>
                        <FontAwesomeIcon icon={faStar} />
                        <label><a href={data?.url} target={'_blank'}>Stars</a></label>
                    </span>
                </div>
            </div>
            <div className="dateLable">
                <label>Created at: {moment(data?.created_at).format('M/DD/YYYY')}</label>
                <label>Last Updated: {moment(data?.updated_at).format('M/DD/YYYY')}</label>
            </div>
            <div className="info">
                <p>Generated by {data?.description}</p>
                <div>
                    {Object.keys(data?.files).map((file, k) => {
                        return (
                            <span key={'file_' + k}>
                                <FontAwesomeIcon icon={faFile} />
                                <label>
                                    <a href={data?.files[file]?.raw_url} target={'_blank'}>{data?.files[file]?.filename}</a>
                                </label>
                            </span>

                        )
                    })}
                </div>
            </div>
        </div>
    )
}

export default Gist
